// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "raft/errno.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace raft {

namespace {

const ::google::protobuf::EnumDescriptor* RaftError_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_raft_2ferrno_2eproto() {
  protobuf_AddDesc_raft_2ferrno_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "raft/errno.proto");
  GOOGLE_CHECK(file != NULL);
  RaftError_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_raft_2ferrno_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_raft_2ferrno_2eproto() {
}

void protobuf_AddDesc_raft_2ferrno_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020raft/errno.proto\022\004raft*+\n\tRaftError\022\n\n"
    "\005ETERM\020\221N\022\022\n\rESTATEMACHINE\020\222N", 69);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "raft/errno.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_raft_2ferrno_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_raft_2ferrno_2eproto {
  StaticDescriptorInitializer_raft_2ferrno_2eproto() {
    protobuf_AddDesc_raft_2ferrno_2eproto();
  }
} static_descriptor_initializer_raft_2ferrno_2eproto_;

const ::google::protobuf::EnumDescriptor* RaftError_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RaftError_descriptor_;
}
bool RaftError_IsValid(int value) {
  switch(value) {
    case 10001:
    case 10002:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace raft

// @@protoc_insertion_point(global_scope)
